# Generated by Django 5.2.3 on 2025-06-15 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('school_class', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('new', 'Very good (like new)'), ('used', 'Normal use'), ('worn', 'Acceptable'), ('poor', 'Very used')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contact_email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='book_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
